// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxwjxljewokzfafuwsmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4d2p4bGpld29remZhZnV3c21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjEzOTIsImV4cCI6MjA2OTE5NzM5Mn0.kunER05Uf3sITuMm_TKteSxzIJMEde1MBcrkjw3bV00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});